version: '3.8'

services:
  web:
    build: .
    container_name: authentication_services
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/authentication_services/data
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
       POSTGRES_PASSWORD: mysecretpassword
    volumes:
       - "E:/Postgresql/data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
          PGADMIN_DEFAULT_EMAIL: root@test@gmail.command
          PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db