
services:
  web:
    build: .
    container_name: authentication_services
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/authentication_services/data
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
       POSTGRES_USER: ${POSTGRES_USERNAME}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
       .env
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      .env
volumes:
   postgresdata:
        external: true