name: Build and Push FastAPI Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
  

      - name: Checkout Repository
        uses: actions/checkout@v3

    

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{secrets.DOCKER_USERNAME}}/authenticationservices-web
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Set permissions for private key
        run: |
             echo "${{secrets.EC2_PEM_KEY }}" > key.pem
             chmod 600 key.pem
      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{secrets.EC2_HOST}}  'sudo docker pull ${{secrets.DOCKER_USERNAME}}/authenticationservices-web:latest'
      - name: Remove running container if exists
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} 'if [ $(sudo docker ps -q -f name=authenticationservices-web) ]; then sudo docker stop authenticationservices-web && sudo docker rm authenticationservices-web; fi'

      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{secrets.EC2_HOST}} 'sudo docker run -d --name authenticationservices-web -p 80:8000 ${{secrets.DOCKER_USERNAME}}/authenticationservices-web:latest'
