name : CICD pipeline
on:
  push:
    branches:
       - master

jobs:
  build_and_push:
   runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Create .env File from Secrets
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
        echo "POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/authentication_services:latest .
    - name: Push Docker Image to Docker Hub
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/authentication_services:latest
